### PR TITLE
Update flyte.org

### PR DESCRIPTION
**Pull request by samhita-alla**
* New dropdown navbar to accommodate a bunch of links (newsletter, office hours, community sync up, etc.)

https://user-images.githubusercontent.com/27777173/150793787-c945369b-280a-4c89-aeea-ab45a732e0db.mov

* Slack pop-up will be shown whenever a user visits flyte.org for the first time (6 months is the frequency)

Screenshot 2022-01-20 at 6 50 40 PM

* Link preview in the carousel

https://user-images.githubusercontent.com/27777173/150793956-b3f7fc2f-38c8-428a-9c3b-a22594f35880.mov

* Modified footer

Screenshot 2022-01-24 at 7 14 12 PM

* Modified swag page title
* Top banner is a carousel now
* Modified GitHub star fetch logic to hit the API every hour cause exceeding the GitHub API rate limit gives a faulty value

UI should be responsive. If there are any issues, let me know!

### CODE REVIEW

**Comment by SandraGH5** [comment]
Cool!
I'd tweak the Slack pop-up message to:
"Join us on Slack to learn more about Flyte, ask questions, or just say hi!" 

I'd also try to find another word to replace "Product" both in the drop-down navbar and footer, even if it's just "Flyte".

**Comment by kumare3** [comment]
I agree instead of product maybe get started?

Also add deploy now

**Comment by cosmicBboy** [comment]
this looks awesome @samhita-alla !

> Slack pop-up will be shown whenever a user visits flyte.org for the first time (6 months is the frequency)

Can we discuss the form factor of this "join slack" call-to-action? This gets a little into subjective taste, but I generally find that centered modal pop-ups (that grey-out the rest of the screen) are kind of invasive, esp. for first-time visitors who just want to know what Flyte is... an alternative to consider would be a collapsible pop-up on the bottom-right corner of the site.

Regardless of the form factor, we should definitely add an analytics event to the clicks on the "Join Flyte Slack" button so that we can track the effectiveness of this change.

**Comment by samhita-alla** [comment]
Regarding replacing "Product" with a better name, "Flyte" and "Get Started" may not be the best choices as they are present in the navbar and dropdown menu, respectively. Could you suggest a better alternative? @SandraGH5 @kumare3 

> Also add deploy now
Do you mean the deploy button? I think it's nice to have it in the docs but not in the flyte.org site.

Regarding Slack call-to-action, it's to get more people to join our Slack channel. That's definitely invasive, but I think that's ok. If someone really has questions to ask or would like to join Slack, it'd be useful. We could add an analytics event as you suggested to track if the call-to-action is useful. Moreover, the pop-up appears 2 minutes after a user visits the site, providing enough time for the user to scroll through the site.

What do you say? @cosmicBboy

**Comment by kumare3** [comment]
Should learn be stay updated or similar? And product be explore?

**Comment by cosmicBboy** [comment]
> Moreover, the pop-up appears 2 minutes after a user visits the site, providing enough time for the user to scroll through the site.

💯 Cool, didn't realize this was the behavior, I think this is okay. We'll also keep track of the bounce rate on the site to see if it causes folks to leave the site, tho 2mins should be enough time for it not to feel that invasive.

**Comment by cosmicBboy** [comment]
re: naming on the top-level nav, my vote would be:

- move "Getting Started" into the "Docs" drop down as the first link. There's already a "Getting Started" button in the center of the hero page. Unlike other marketing sites, like [stripe](https://stripe.com/), Flyte doesn't have multiple products, it's a single product in itself.
- Move "Roadmap" and "Current Deployment" to the "Community" dropdown.
- Reorder the top-level nav buttons to reflect order of importance
  - Docs: IMO this is the most important for new potential users assessing the quality of a software product
  - Learn: learning concepts behind Flyte is great, but secondary to seeing how the code looks like and how it works
  - Community: This is further in the user journey when folks need support
  - Github stars badge

**Comment by samhita-alla** [comment]
@cosmicBboy @kumare3 incorporated all suggestions.

image

**Review by kumare3 — APPROVED** [review]

**Pull request merged**
