### PR TITLE
Add swag giveaway page

### PR DESCRIPTION
**Pull request by samhita-alla**
Signed-off-by: Samhita Alla <aallasamhita@gmail.com>

This PR adds a swag giveaway page. I segregated the contributors into three levels: **Flyte Pilot, Flyte Host/Hostess, Flyte Passenger** (does the terminology look ok?). The link to the swag page is added as an icon to the navbar.

After this PR is merged, the newly added page looks as follows:

https://user-images.githubusercontent.com/27777173/149095454-4a94a46e-d183-4dd1-a4af-d5212454b76f.mov

Also,
- Updated Flyte release in the top banner
- Cleaned up some code

### CODE REVIEW

**Comment by samhita-alla** [comment]
@SandraGH5, after this PR is merged, can we advertise this page saying there's a chance to win swag if you contribute to Flyte?

**Comment by SandraGH5** [comment]
Sure @samhita-alla

**Comment by kumare3** [comment]
@samhita-alla can we make `Flyte host/hostess` -> `Flyte crew`

**Comment by samhita-alla** [comment]
> @samhita-alla can we make `Flyte host/hostess` -> `Flyte crew`

Um, I think it should be a concrete noun? Crew denotes a set of people.
Host/hostess is kinda off, but I didn't find a better terminology.

**Comment by cosmicBboy** [comment]
My two cents: there's no need to gender it, Flyte Host is perfectly fine, or Flyte Crew Member

**Comment by samhita-alla** [comment]
> My two cents: there's no need to gender it, Flyte Host is perfectly fine, or Flyte Crew Member

If that's the case, then awesome! I'll modify it to Flyte Host (Flyte Crew Member is relatively long!).

**Pull request merged**
