### PR TITLE
Add a new feature & feature image

### PR DESCRIPTION
**Pull request by samhita-alla**
Signed-off-by: Samhita Alla <aallasamhita@gmail.com>

**Let's merge this after the logos get merged.**

* Added a new feature image as we do not have an additional SVG. The SVG mapped to the battle-tested feature in flyte.org doesn't seem right; hence mapped it to the new feature in this PR. @kumare3 -- let me know if this image is okay.
image
image

### CODE REVIEW

**Comment by kumare3** [comment]
@samhita-alla  the previous logos were nicer, I do not like this maze. Also everyone approved for their previous logos laid out nicely

**Comment by samhita-alla** [comment]
> @samhita-alla the previous logos were nicer, I do not like this maze. Also everyone approved for their previous logos laid out nicely

The previous logos will be there. This is in addition to that. If we're to add an additional feature, we require an additional SVG image to accompany it, else it will be a repetition of images. Let me know if you've any ideas.

**Comment by samhita-alla** [comment]
@kumare3 -- I've modified the image now. Let me know if this is okay.

**Comment by kumare3** [comment]
This is awesome - we should say Apache 2.0, LF ai and data incubating

**Comment by samhita-alla** [comment]
> This is awesome - we should say Apache 2.0, LF ai and data incubating

Please check now.

**Review by kumare3 — APPROVED** [review]

**Pull request merged**
