### PR TITLE
Announce talks and add Google analytics

### PR DESCRIPTION
**Pull request by samhita-alla**
Signed-off-by: Samhita Alla <aallasamhita@gmail.com>

https://user-images.githubusercontent.com/27777173/131131628-3e0b38e0-7e4e-405a-916f-f591189c0ec7.mov

### CODE REVIEW

**Comment by samhita-alla** [comment]
@kumare3 and @SandraGH5: I have added cards in the UI to announce our talks. Let me know if this looks okay. Also, the cards redirect to the OSPOCon links when one clicks on them.

**Review by kumare3 — APPROVED** [review]
How can Sandra add new content? But this is s awesome

**Comment by cosmicBboy** [comment]
Nice!

One comment is to consider simplifying the color palette on the conference title text (e.g. like the purple on the "Get Started" button), the multi-colored scheme is a little visually distracting

**Comment by kumare3** [comment]
Also
I want to make sure we add about big feature releases and blogs here

**Comment by samhita-alla** [comment]
https://user-images.githubusercontent.com/27777173/131327998-73627ba3-c4f7-4108-ad0c-87620bab1028.mov

> One comment is to consider simplifying the color palette on the conference title text (e.g. like the purple on the "Get Started" button), the multi-colored scheme is a little visually distracting

@cosmicBboy Simplified the color palette.

>  I want to make sure we add about big feature releases and blogs here

@kumare3 Feature release and blog templates are available now.

> How can Sandra add new content?

@SandraGH5 Please check the "How to Add/Modify Announcements" section in the README. 
For now, both feature- and blog-related card templates are commented. If you want to add one in the future, just uncomment; if you want to add more announcements, copy the concerning card template code and paste it anywhere in the card series. Then, modify the content. You can find more details in the README. Please let me know of any difficulties you may come across.

**Comment by samhita-alla** [comment]
@kumare3 Let me know if we can merge these changes.

**Review by kumare3 — APPROVED** [review]

**Review by SandraGH5 — COMMENTED** [review]
Looks good Samhita! 
I agree with Niels to simplify the colors. Like the blue in the Release card has 2 shades of blue - just one shade would be ideal. Also the green in the Blogs card has 2 shades of green, and the pink for the others.
I will check how to update content and let you know if I run into anything.

**Pull request merged**
